@startuml

title "Get User By Email"

actor User as user

participant "app.go" as app
participant "user.go" as Users
participant "GetAssignUserNamespaces" as handler
database Database as DB

group "API Call"
    user -> app : GET: /find/user/
    user -> app : PATH : emaill
end
Users -> handler
handler -> DB
handler -> user
@enduml