@startuml
title "Set Current Workspace"

actor User as user

participant "App.go" as app
participant "users.go" as route
participant "UserSession" as Session
database Database as DB
participant "handler" as handler

group "API Call"
user -> app : POST : /api/namespace
end
app -> route : SetCurrentNamespace()


@enduml