@startuml

title "Delete Single Menu"

actor User as user

participant "app.go" as app
participant "adminconfig.go" as route
database Database as DB

group  "API Call"
user    -> app : DELETE: /api/adminconfig/menu
user    -> app : body: models.Menu
end
app     -> route: DelMenu()
route <-> DB: Delete
user <- route:  return successMessage


@enduml
