import { useAxiosPost } from '@/shared/libs/api/request.ts';
import { IAxiosResponse, RequestBodyWrapper } from '@/shared/libs';
import {
  IUserInfoResponse,
  UserInformationTableType,
  UserWorkspaceTableType,
} from '@/entities';

const LOGIN_URL = 'auth/login';
const GET_USER_INFO = 'Getuserinfo';
const GET_USER_LIST = 'GetUsers';
const ADD_USER = 'Createuser';

export function useGetLogin<T, D>(loginData: D | null) {
  const requestBodyWrapper: Required<
    Pick<RequestBodyWrapper<D | null>, 'request'>
  > = {
    request: loginData,
  };
  return useAxiosPost<IAxiosResponse<T>, RequestBodyWrapper<D | null>>(
    LOGIN_URL,
    requestBodyWrapper,
  );
}

export function useGetUserRole<IUserResponse, D = any>() {
  return useAxiosPost<IUserResponse, D | null>(GET_USER_INFO, null);
}

export function getUserList() {
  return useAxiosPost<IAxiosResponse<IUserInfoResponse[]>, null>(
    GET_USER_LIST,
    null,
  );
}

export function useAddUser<T, D>(userData: D | null) {
  const requestBodyWrapper: Required<
    Pick<RequestBodyWrapper<D | null>, 'request'>
  > = {
    request: userData,
  };

  return useAxiosPost<IAxiosResponse<T>, RequestBodyWrapper<D | null>>(
    ADD_USER,
    requestBodyWrapper,
  );
}

export const tempGetUserList = (): Partial<
  Record<UserInformationTableType | UserWorkspaceTableType, any>
>[] => {
  return [
    {
      userId: 'mcpsuper',
      name: '김이름',
      description: 'description',
      company: 'company',
      department: 'department',
      group: ['group1', 'group2', 'group3'],
      approved: { state: true, data: 'Approved' },
      callInvite: 'callInvite',
      receiveInvite: 'receiveInvite',
      defaultRoles: ['role1', 'role2', 'role3'],
      workspace: 'WorkspaceName',
      role: 'admin',
      invited: new Date(),
      removeAction: { action: true },
    },
    {
      userId: 'emailId@mz.co.kr',
      name: '강이름',
      description: 'description',
      company: 'company',
      department: 'department',
      group: ['group1', 'group2', 'group3'],
      approved: { state: true, data: 'Approved' },
      callInvite: 'callInvite',
      receiveInvite: 'receiveInvite',
      defaultRoles: ['role1', 'role2', 'role3'],
      workspace: 'WorkspaceName',
      role: 'admin',
      invited: new Date(),
      removeAction: { action: true },
    },
    {
      userId: 'emailId@mz.co.kr',
      name: '고이름',
      description: 'description',
      company: 'company',
      department: 'department',
      group: ['group1', 'group2', 'group3'],
      approved: { state: true, data: 'Approved' },
      callInvite: 'callInvite',
      receiveInvite: 'receiveInvite',
      defaultRoles: ['role1', 'role2', 'role3'],
      workspace: 'WorkspaceName',
      role: 'admin',
      invited: new Date(),
      removeAction: { action: true },
    },
    {
      userId: 'emailId@mz.co.kr',
      name: '이이름',
      description: 'description',
      company: 'company',
      department: 'department',
      group: ['group1', 'group2', 'group3'],
      approved: { state: true, data: 'Approved' },
      callInvite: 'callInvite',
      receiveInvite: 'receiveInvite',
      defaultRoles: ['role1', 'role2', 'role3'],
      workspace: 'WorkspaceName',
      role: 'admin',
      invited: new Date(),
      removeAction: { action: true },
    },
    {
      userId: 'emailId@mz.co.kr',
      name: '김이름',
      description: 'description',
      company: 'company',
      department: 'department',
      group: ['group1', 'group2', 'group3'],
      approved: { state: true, data: 'Approved' },
      callInvite: 'callInvite',
      receiveInvite: 'receiveInvite',
      defaultRoles: ['role1', 'role2', 'role3'],
      workspace: 'WorkspaceName',
      role: 'admin',
      invited: new Date(),
      removeAction: { action: true },
    },
    {
      userId: 'emailId@mz.co.kr',
      name: '김이름',
      description: 'description',
      company: 'company',
      department: 'department',
      group: ['group1', 'group2', 'group3'],
      approved: { state: true, data: 'Approved' },
      callInvite: 'callInvite',
      receiveInvite: 'receiveInvite',
      defaultRoles: ['role1', 'role2', 'role3'],
      workspace: 'WorkspaceName',
      role: 'admin',
      invited: new Date(),
      removeAction: { action: true },
    },
    {
      userId: 'emailId@mz.co.kr',
      name: '김이름',
      description: 'description',
      company: 'company',
      department: 'department',
      group: ['group1', 'group2', 'group3'],
      approved: { state: true, data: 'Approved' },
      callInvite: 'callInvite',
      receiveInvite: 'receiveInvite',
      defaultRoles: ['role1', 'role2', 'role3'],
      workspace: 'WorkspaceName',
      role: 'admin',
      invited: new Date(),
      removeAction: { action: true },
    },
    {
      userId: 'emailId@mz.co.kr',
      name: '김이름',
      description: 'description',
      company: 'company',
      department: 'department',
      group: ['group1', 'group2', 'group3'],
      approved: { state: true, data: 'Approved' },
      callInvite: 'callInvite',
      receiveInvite: 'receiveInvite',
      defaultRoles: ['role1', 'role2', 'role3'],
      workspace: 'WorkspaceName',
      role: 'admin',
      invited: new Date(),
      removeAction: { action: true },
    },
    {
      userId: 'emailId@mz.co.kr',
      name: '김이름',
      description: 'description',
      company: 'company',
      department: 'department',
      group: ['group1', 'group2', 'group3'],
      approved: { state: true, data: 'Approved' },
      callInvite: 'callInvite',
      receiveInvite: 'receiveInvite',
      defaultRoles: ['role1', 'role2', 'role3'],
      workspace: 'WorkspaceName',
      role: 'admin',
      invited: new Date(),
      removeAction: { action: true },
    },
    {
      userId: 'emailId@mz.co.kr',
      name: '김이름',
      description: 'description',
      company: 'company',
      department: 'department',
      group: ['group1', 'group2', 'group3'],
      approved: { state: true, data: 'Approved' },
      callInvite: 'callInvite',
      receiveInvite: 'receiveInvite',
      defaultRoles: ['role1', 'role2', 'role3'],
      workspace: 'WorkspaceName',
      role: 'admin',
      invited: new Date(),
      removeAction: { action: true },
    },
    {
      userId: 'emailId@mz.co.kr',
      name: '김이름',
      description: 'description',
      company: 'company',
      department: 'department',
      group: ['group1', 'group2', 'group3'],
      approved: { state: true, data: 'Approved' },
      callInvite: 'callInvite',
      receiveInvite: 'receiveInvite',
      defaultRoles: ['role1', 'role2', 'role3'],
      workspace: 'WorkspaceName',
      role: 'admin',
      invited: new Date(),
      removeAction: { action: true },
    },
    {
      userId: 'emailId@mz.co.kr',
      name: '김이름',
      description: 'description',
      company: 'company',
      department: 'department',
      group: ['group1', 'group2', 'group3'],
      approved: { state: true, data: 'Approved' },
      callInvite: 'callInvite',
      receiveInvite: 'receiveInvite',
      defaultRoles: ['role1', 'role2', 'role3'],
      workspace: 'WorkspaceName',
      role: 'admin',
      invited: new Date(),
      removeAction: { action: true },
    },
    {
      userId: 'emailId@mz.co.kr',
      name: '김이름',
      description: 'description',
      company: 'company',
      department: 'department',
      group: ['group1', 'group2', 'group3'],
      approved: { state: true, data: 'Approved' },
      callInvite: 'callInvite',
      receiveInvite: 'receiveInvite',
      defaultRoles: ['role1', 'role2', 'role3'],
      workspace: 'WorkspaceName',
      role: 'admin',
      invited: new Date(),
      removeAction: { action: true },
    },
    {
      userId: 'emailId@mz.co.kr',
      name: '김이름',
      description: 'description',
      company: 'company',
      department: 'department',
      group: ['group1', 'group2', 'group3'],
      approved: { state: true, data: 'Approved' },
      callInvite: 'callInvite',
      receiveInvite: 'receiveInvite',
      defaultRoles: ['role1', 'role2', 'role3'],
      workspace: 'WorkspaceName',
      role: 'admin',
      invited: new Date(),
      removeAction: { action: true },
    },
    {
      userId: 'emailId@mz.co.kr',
      name: '김이름',
      description: 'description',
      company: 'company',
      department: 'department',
      group: ['group1', 'group2', 'group3'],
      approved: { state: true, data: 'Approved' },
      callInvite: 'callInvite',
      receiveInvite: 'receiveInvite',
      defaultRoles: ['role1', 'role2', 'role3'],
      workspace: 'WorkspaceName',
      role: 'admin',
      invited: new Date(),
      removeAction: { action: true },
    },
    {
      userId: 'emailId@mz.co.kr',
      name: '김이름',
      description: 'description',
      company: 'company',
      department: 'department',
      group: ['group1', 'group2', 'group3'],
      approved: { state: true, data: 'Approved' },
      callInvite: 'callInvite',
      receiveInvite: 'receiveInvite',
      defaultRoles: ['role1', 'role2', 'role3'],
      workspace: 'WorkspaceName',
      role: 'admin',
      invited: new Date(),
      removeAction: { action: true },
    },
    {
      userId: 'emailId@mz.co.kr',
      name: '김이름',
      description: 'description',
      company: 'company',
      department: 'department',
      group: ['group1', 'group2', 'group3'],
      approved: { state: true, data: 'Approved' },
      callInvite: 'callInvite',
      receiveInvite: 'receiveInvite',
      defaultRoles: ['role1', 'role2', 'role3'],
      workspace: 'WorkspaceName',
      role: 'admin',
      invited: new Date(),
      removeAction: { action: true },
    },
    {
      userId: 'emailId@mz.co.kr',
      name: '김이름',
      description: 'description',
      company: 'company',
      department: 'department',
      group: ['group1', 'group2', 'group3'],
      approved: { state: true, data: 'Approved' },
      callInvite: 'callInvite',
      receiveInvite: 'receiveInvite',
      defaultRoles: ['role1', 'role2', 'role3'],
      workspace: 'WorkspaceName',
      role: 'admin',
      invited: new Date(),
      removeAction: { action: true },
    },
    {
      userId: 'emailId@mz.co.kr',
      name: '김이름',
      description: 'description',
      company: 'company',
      department: 'department',
      group: ['group1', 'group2', 'group3'],
      approved: { state: true, data: 'Approved' },
      callInvite: 'callInvite',
      receiveInvite: 'receiveInvite',
      defaultRoles: ['role1', 'role2', 'role3'],
      workspace: 'WorkspaceName',
      role: 'admin',
      invited: new Date(),
      removeAction: { action: true },
    },
    {
      userId: 'emailId@mz.co.kr',
      name: '김이름',
      description: 'description',
      company: 'company',
      department: 'department',
      group: ['group1', 'group2', 'group3'],
      approved: { state: true, data: 'Approved' },
      callInvite: 'callInvite',
      receiveInvite: 'receiveInvite',
      defaultRoles: ['role1', 'role2', 'role3'],
      workspace: 'WorkspaceName',
      role: 'admin',
      invited: new Date(),
      removeAction: { action: true },
    },
    {
      userId: 'emailId@mz.co.kr',
      name: '김이름',
      description: 'description',
      company: 'company',
      department: 'department',
      group: ['group1', 'group2', 'group3'],
      approved: { state: true, data: 'Approved' },
      callInvite: 'callInvite',
      receiveInvite: 'receiveInvite',
      defaultRoles: ['role1', 'role2', 'role3'],
      workspace: 'WorkspaceName',
      role: 'admin',
      invited: new Date(),
      removeAction: { action: true },
    },
    {
      userId: 'emailId@mz.co.kr',
      name: '김이름',
      description: 'description',
      company: 'company',
      department: 'department',
      group: ['group1', 'group2', 'group3'],
      approved: { state: true, data: 'Approved' },
      callInvite: 'callInvite',
      receiveInvite: 'receiveInvite',
      defaultRoles: ['role1', 'role2', 'role3'],
      workspace: 'WorkspaceName',
      role: 'admin',
      invited: new Date(),
      removeAction: { action: true },
    },
    {
      userId: 'emailId@mz.co.kr',
      name: '김이름',
      description: 'description',
      company: 'company',
      department: 'department',
      group: ['group1', 'group2', 'group3'],
      approved: { state: true, data: 'Approved' },
      callInvite: 'callInvite',
      receiveInvite: 'receiveInvite',
      defaultRoles: ['role1', 'role2', 'role3'],
      workspace: 'WorkspaceName',
      role: 'admin',
      invited: new Date(),
      removeAction: { action: true },
    },
    {
      userId: 'emailId@mz.co.kr',
      name: '김이름',
      description: 'description',
      company: 'company',
      department: 'department',
      group: ['group1', 'group2', 'group3'],
      approved: { state: true, data: 'Approved' },
      callInvite: 'callInvite',
      receiveInvite: 'receiveInvite',
      defaultRoles: ['role1', 'role2', 'role3'],
      workspace: 'WorkspaceName',
      role: 'admin',
      invited: new Date(),
      removeAction: { action: true },
    },
    {
      userId: 'emailId@mz.co.kr',
      name: '김이름',
      description: 'description',
      company: 'company',
      department: 'department',
      group: ['group1', 'group2', 'group3'],
      approved: { state: true, data: 'Approved' },
      callInvite: 'callInvite',
      receiveInvite: 'receiveInvite',
      defaultRoles: ['role1', 'role2', 'role3'],
      workspace: 'WorkspaceName',
      role: 'admin',
      invited: new Date(),
      removeAction: { action: true },
    },
    {
      userId: 'emailId@mz.co.kr',
      name: '김이름',
      description: 'description',
      company: 'company',
      department: 'department',
      group: ['group1', 'group2', 'group3'],
      approved: { state: true, data: 'Approved' },
      callInvite: 'callInvite',
      receiveInvite: 'receiveInvite',
      defaultRoles: ['role1', 'role2', 'role3'],
      workspace: 'WorkspaceName',
      role: 'admin',
      invited: new Date(),
      removeAction: { action: true },
    },
    {
      userId: 'emailId@mz.co.kr',
      name: '김이름',
      description: 'description',
      company: 'company',
      department: 'department',
      group: ['group1', 'group2', 'group3'],
      approved: { state: true, data: 'Approved' },
      callInvite: 'callInvite',
      receiveInvite: 'receiveInvite',
      defaultRoles: ['role1', 'role2', 'role3'],
      workspace: 'WorkspaceName',
      role: 'admin',
      invited: new Date(),
      removeAction: { action: true },
    },
    {
      userId: 'emailId@mz.co.kr',
      name: '김이름',
      description: 'description',
      company: 'company',
      department: 'department',
      group: ['group1', 'group2', 'group3'],
      approved: { state: true, data: 'Approved' },
      callInvite: 'callInvite',
      receiveInvite: 'receiveInvite',
      defaultRoles: ['role1', 'role2', 'role3'],
      workspace: 'WorkspaceName',
      role: 'admin',
      invited: new Date(),
      removeAction: { action: true },
    },
    {
      userId: 'emailId@mz.co.kr',
      name: '김이름',
      description: 'description',
      company: 'company',
      department: 'department',
      group: ['group1', 'group2', 'group3'],
      approved: { state: true, data: 'Approved' },
      callInvite: 'callInvite',
      receiveInvite: 'receiveInvite',
      defaultRoles: ['role1', 'role2', 'role3'],
      workspace: 'WorkspaceName',
      role: 'admin',
      invited: new Date(),
      removeAction: { action: true },
    },
    {
      userId: 'emailId@mz.co.kr',
      name: '김이름',
      description: 'description',
      company: 'company',
      department: 'department',
      group: ['group1', 'group2', 'group3'],
      approved: { state: true, data: 'Approved' },
      callInvite: 'callInvite',
      receiveInvite: 'receiveInvite',
      defaultRoles: ['role1', 'role2', 'role3'],
      workspace: 'WorkspaceName',
      role: 'admin',
      invited: new Date(),
      removeAction: { action: true },
    },
    {
      userId: 'emailId@mz.co.kr',
      name: '김이름',
      description: 'description',
      company: 'company',
      department: 'department',
      group: ['group1', 'group2', 'group3'],
      approved: { state: true, data: 'Approved' },
      callInvite: 'callInvite',
      receiveInvite: 'receiveInvite',
      defaultRoles: ['role1', 'role2', 'role3'],
      workspace: 'WorkspaceName',
      role: 'admin',
      invited: new Date(),
      removeAction: { action: true },
    },
    {
      userId: 'emailId@mz.co.kr',
      name: '김이름',
      description: 'description',
      company: 'company',
      department: 'department',
      group: ['group1', 'group2', 'group3'],
      approved: { state: true, data: 'Approved' },
      callInvite: 'callInvite',
      receiveInvite: 'receiveInvite',
      defaultRoles: ['role1', 'role2', 'role3'],
      workspace: 'WorkspaceName',
      role: 'admin',
      invited: new Date(),
      removeAction: { action: true },
    },
    {
      userId: 'emailId@mz.co.kr',
      name: '김이름',
      description: 'description',
      company: 'company',
      department: 'department',
      group: ['group1', 'group2', 'group3'],
      approved: { state: true, data: 'Approved' },
      callInvite: 'callInvite',
      receiveInvite: 'receiveInvite',
      defaultRoles: ['role1', 'role2', 'role3'],
      workspace: 'WorkspaceName',
      role: 'admin',
      invited: new Date(),
      removeAction: { action: true },
    },
    {
      userId: 'emailId@mz.co.kr',
      name: '김이름',
      description: 'description',
      company: 'company',
      department: 'department',
      group: ['group1', 'group2', 'group3'],
      approved: { state: true, data: 'Approved' },
      callInvite: 'callInvite',
      receiveInvite: 'receiveInvite',
      defaultRoles: ['role1', 'role2', 'role3'],
      workspace: 'WorkspaceName',
      role: 'admin',
      invited: new Date(),
      removeAction: { action: true },
    },
    {
      userId: 'emailId@mz.co.kr',
      name: '김이름',
      description: 'description',
      company: 'company',
      department: 'department',
      group: ['group1', 'group2', 'group3'],
      approved: { state: true, data: 'Approved' },
      callInvite: 'callInvite',
      receiveInvite: 'receiveInvite',
      defaultRoles: ['role1', 'role2', 'role3'],
      workspace: 'WorkspaceName',
      role: 'admin',
      invited: new Date(),
      removeAction: { action: true },
    },
    {
      userId: 'emailId@mz.co.kr',
      name: '김이름',
      description: 'description',
      company: 'company',
      department: 'department',
      group: ['group1', 'group2', 'group3'],
      approved: { state: true, data: 'Approved' },
      callInvite: 'callInvite',
      receiveInvite: 'receiveInvite',
      defaultRoles: ['role1', 'role2', 'role3'],
      workspace: 'WorkspaceName',
      role: 'admin',
      invited: new Date(),
      removeAction: { action: true },
    },
    {
      userId: 'emailId@mz.co.kr',
      name: '김이름',
      description: 'description',
      company: 'company',
      department: 'department',
      group: ['group1', 'group2', 'group3'],
      approved: { state: true, data: 'Approved' },
      callInvite: 'callInvite',
      receiveInvite: 'receiveInvite',
      defaultRoles: ['role1', 'role2', 'role3'],
      workspace: 'WorkspaceName',
      role: 'admin',
      invited: new Date(),
      removeAction: { action: true },
    },
    {
      userId: 'emailId@mz.co.kr',
      name: '김이름',
      description: 'description',
      company: 'company',
      department: 'department',
      group: ['group1', 'group2', 'group3'],
      approved: { state: true, data: 'Approved' },
      callInvite: 'callInvite',
      receiveInvite: 'receiveInvite',
      defaultRoles: ['role1', 'role2', 'role3'],
      workspace: 'WorkspaceName',
      role: 'admin',
      invited: new Date(),
      removeAction: { action: true },
    },
    {
      userId: 'emailId@mz.co.kr',
      name: '김이름',
      description: 'description',
      company: 'company',
      department: 'department',
      group: ['group1', 'group2', 'group3'],
      approved: { state: true, data: 'Approved' },
      callInvite: 'callInvite',
      receiveInvite: 'receiveInvite',
      defaultRoles: ['role1', 'role2', 'role3'],
      workspace: 'WorkspaceName',
      role: 'admin',
      invited: new Date(),
      removeAction: { action: true },
    },
    {
      userId: 'emailId@mz.co.kr',
      name: '김이름',
      description: 'description',
      company: 'company',
      department: 'department',
      group: ['group1', 'group2', 'group3'],
      approved: { state: true, data: 'Approved' },
      callInvite: 'callInvite',
      receiveInvite: 'receiveInvite',
      defaultRoles: ['role1', 'role2', 'role3'],
      workspace: 'WorkspaceName',
      role: 'admin',
      invited: new Date(),
      removeAction: { action: true },
    },
    {
      userId: 'emailId@mz.co.kr',
      name: '김이름',
      description: 'description',
      company: 'company',
      department: 'department',
      group: ['group1', 'group2', 'group3'],
      approved: { state: true, data: 'Approved' },
      callInvite: 'callInvite',
      receiveInvite: 'receiveInvite',
      defaultRoles: ['role1', 'role2', 'role3'],
      workspace: 'WorkspaceName',
      role: 'admin',
      invited: new Date(),
      removeAction: { action: true },
    },
    {
      userId: 'emailId@mz.co.kr',
      name: '김이름',
      description: 'description',
      company: 'company',
      department: 'department',
      group: ['group1', 'group2', 'group3'],
      approved: { state: true, data: 'Approved' },
      callInvite: 'callInvite',
      receiveInvite: 'receiveInvite',
      defaultRoles: ['role1', 'role2', 'role3'],
      workspace: 'WorkspaceName',
      role: 'admin',
      invited: new Date(),
      removeAction: { action: true },
    },
    {
      userId: 'emailId@mz.co.kr',
      name: '김이름',
      description: 'description',
      company: 'company',
      department: 'department',
      group: ['group1', 'group2', 'group3'],
      approved: { state: true, data: 'Approved' },
      callInvite: 'callInvite',
      receiveInvite: 'receiveInvite',
      defaultRoles: ['role1', 'role2', 'role3'],
      workspace: 'WorkspaceName',
      role: 'admin',
      invited: new Date(),
      removeAction: { action: true },
    },
    {
      userId: 'emailId@mz.co.kr',
      name: '김이름',
      description: 'description',
      company: 'company',
      department: 'department',
      group: ['group1', 'group2', 'group3'],
      approved: { state: true, data: 'Approved' },
      callInvite: 'callInvite',
      receiveInvite: 'receiveInvite',
      defaultRoles: ['role1', 'role2', 'role3'],
      workspace: 'WorkspaceName',
      role: 'admin',
      invited: new Date(),
      removeAction: { action: true },
    },
    {
      userId: 'emailId@mz.co.kr',
      name: '김이름',
      description: 'description',
      company: 'company',
      department: 'department',
      group: ['group1', 'group2', 'group3'],
      approved: { state: true, data: 'Approved' },
      callInvite: 'callInvite',
      receiveInvite: 'receiveInvite',
      defaultRoles: ['role1', 'role2', 'role3'],
      workspace: 'WorkspaceName',
      role: 'admin',
      invited: new Date(),
      removeAction: { action: true },
    },
  ];
};
