@startuml

title "Delete single Region"

actor User as user

participant "app.go" as app
participant "connection.go" as route
database Database as DB

group  "API Call"
user    -> app : DELETE: /api/settings/connection/region
user    -> app : BODY: models.Region
end
app     -> route: RegionDelete()
route <-> DB: Delete Regions
user <- route:  return successMessage


@enduml
