@startuml

title "Get Credential List"

actor User as user

participant "app.go" as app
participant "connection.go" as route
participant "CloudConnectionHandler.go" as handler
database Database as DB

box "External Module"
participant "cb-spider" as spider
end box

group  "API Call"
user    -> app : GET: /api/settings/connection/credential
user    -> app : PARAM: is_cb, BODY: models.Credential
end
app     -> route: CredentialList()

alt is_cb == "N"
    route     -> handler: MconCredentialList(credential *models.Credential)
    handler <-> DB: fetch Credential list
    route <- handler: []models.Credential
    user <- route:  return credentialList
else is_cb == "Y"
    route   -> handler: SpiderDriverGet(driverlName string)
    handler <-> spider: http request to fetch spider credential list
    route <- handler: []spider.CredentialInfo
    user <- route:  return credentialList
end

@enduml
