@startuml

title "Generate connection by credential"

actor User as user

participant "app.go" as app
participant "connection.go" as route
participant "CloudConnectionHandler.go" as handler
database Database as DB

box "External Module"
participant "cb-spider" as spider
end box

group "API Call"
    user    -> app : GET: /api/settings/connection/generate/bycredential
    user    -> app : QUERY: providerId, credentialName
end

app     -> route: GenerateConnectionsByCredential()
route     -> handler: GenerateConnectionsByCredential(paramProviderID string, paramCredentialName string)
handler -> handler: GetDriverByProvider(providerId string)
handler -> DB: fetch driver by provider id

handler -> hanlder: GetCloudConnectionConfigList()
handler -> spider: fetch all connection list

handler -> hanlder: GetRegionList()
handler -> spider: fetch all connection list

loop regionList
    handler -> handler: CheckExistsCloudConnection(connectionView views.ViewCloudConnection)
    handler -> DB: check whether exists or not

    handler -> handler: CheckExistsCredential(providerName string, credentialName string)
    handler -> DB: check whether exists or not
    alt !exists
        handler -> DB: validate and create
    end

    handler -> handler: MconCredentialGet(credential *models.Credential)
    handler -> handler: MconRegionGet(region *models.Region)

    handler -> handler: RegCloudConnectionConfig(cloudConnectionConfigInfo *spider.CloudConnectionConfigInfo)
    handler -> spider: create cloud connection configuration
    handler -> DB: validate and create cloud connection
end
route <- handler: 
user <- route : return successMessages
@enduml
