@startuml

title "Create Credential"

actor User as user

participant "app.go" as app
participant "connection.go" as route
participant "CloudConnectionHandler.go" as handler
database Database as DB

box "External Module"
participant "cb-spider" as spider
end box

group "API Call"
    user    -> app : POST: /api/settings/connection/credential
    user    -> app : QUERY: is_cb, BODY: spider.CredentialInfo
end

app     -> route: CredentialCreate()
route     -> handler: RegCredential(credentialInfo *spider.CredentialInfo)
handler <-> spider: http request to create credential
route <- handler: *spider.CredentialInfo

alt is_cb == "N"
    route     -> handler: MconCredentialCreate(credential *models.Credential)
    handler <-> DB: Create Credential
    route <- handler
end

user <- route : return successMessagexs
@enduml
