@startuml

title "Get spider Connection"

actor User as user

participant "app.go" as app
participant "connection.go" as route
participant "CloudConnectionHandler.go" as handler
box "External Module"
participant "cb-spider" as spider
end box

group  "API Call"
user    -> app : GET: /api/settings/connection/spider/id/{connectionId}
user    -> app : PATH: connectionId
end
app     -> route: SpiderConnectionGet()
route     -> handler: GetCloudConnectionConfigData(configName string)
handler <-> spider: http request to spider module
route <- handler: spider.CloudConnectionConfigInfo
user <- route:  return connectionInfo


@enduml
