@startuml

title "Get Credential"

actor User as user

participant "app.go" as app
participant "connection.go" as route
participant "CloudConnectionHandler.go" as handler
database Database as DB

box "External Module"
participant "cb-spider" as spider
end box

group  "API Call"
user    -> app : GET: /api/settings/connection/credential/id/{credential}
user    -> app : PATH: path, QUERY: is_cb, BODY: models.Credential
end

app     -> route: CredentialGet()

alt is_cb == "N"
    route     -> handler: MconCredentialGet(credential *models.Credential)
    handler <-> DB: fetch Credential
    route <- handler: models.Credential
    user <- route:  return credentialInfo
else is_cb == "Y"
    route   -> handler: GetCredentialData(credentialName string)
    handler <-> spider: http request to fetch spider credential
    route <- handler: *spider.CredentialInfo
    user <- route:  return credentialInfo
end

@enduml
